B marcos graciano
NExT-2023-1/n04-controle-de-armazenamento pull request #11
Opened 2023-09-19 18:28 UTC by marcosgrac

Scripts para acesso e transferência de arquivos na Cloud AWS

2023-09-19 18:36 UTC, romuloquidutefilho requested changes
Também corrigir no arquivo CloudServiceApplication para ficar conforme abaixo:

```
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class }) 
public class CloudServiceApplication
```

2023-09-19 18:36 UTC, romuloquidutefilho commented on src/main/java/com/next2023/cloud_service/repositories/ArquivosRepoisitory.java
> +//@Repository
```suggestion
@Repository
```

2023-09-19 18:36 UTC, romuloquidutefilho commented on src/main/java/com/next2023/cloud_service/repositories/UsuarioRepository.java
> +//@Repository
```suggestion
@Repository
```

2023-09-19 18:36 UTC, romuloquidutefilho commented on src/main/java/com/next2023/cloud_service/entities/Arquivos.java
> +
```suggestion
```

2023-09-19 18:36 UTC, romuloquidutefilho commented on src/main/java/com/next2023/cloud_service/util/ArmazenamentoProperties.java
> +@PropertySource("application.properties")
```suggestion
```
Acredito que esse linha não seja necessária

2023-09-19 23:45 UTC, romuloquidutefilho requested changes

2023-09-19 23:45 UTC, romuloquidutefilho commented on src/main/resources/application.properties
Esse arquivo acho que foi deletado indevidamente

2023-09-19 23:45 UTC, romuloquidutefilho commented on src/main/java/com/next2023/cloud_service/services/AwsConfigService.java
> +        PutObjectRequest request = new PutObjectRequest(bucketName, fileName, new File(filePath));
Pegar arquivo em formato stream ou array de bytes, invés de pegar o arquivo fisicamente

2023-09-19 23:45 UTC, romuloquidutefilho commented on src/main/java/com/next2023/cloud_service/services/AwsConfigService.java
> +        FileUtils.copyInputStreamToFile(inputStream, new File("." + File.separator + fileName));
retornar  arquivo em formato stream ou array de bytes, invés de pegar o arquivo fisicamente

2023-09-20 00:38 UTC, marcosgrac commented on src/main/resources/application.properties
Foi proposital para resolver a questão da quarentena da AWS.
Fixei o valor a seguir para o arquivo de propriedade e fiz com que o git parasse de enxergar o arquivo de propriedade. Conteúdo do arquivo:
awsS3.accessKey = <<Colocar a access key da AWS>>
awsS3.secretKey = <<Colocar a access key da AWS>>

Dessa forma, a chave não ficará disponível no github.

2023-09-20 10:37 UTC, romuloquidutefilho requested changes
O arquivo application.properties foi deletado.

2023-09-20 15:57 UTC, romuloquidutefilho approved these changes

2023-09-20 15:57 UTC, romuloquidutefilho commented on src/main/resources/application.properties
> +awsS3.secretKey = <<Colocar a access key da AWS>>
```suggestion
awsS3.accessKey=<Colocar a access key da AWS>
awsS3.secretKey=<Colocar a access key da AWS>
```

2023-09-20 15:58 UTC, merged